### ISSUE TITLE
Switches not switching

### ISSUE THREAD

**Issue by mensoh** [Luc-S/Toon-HASS#16]
I've configured my lights from home assistant in toon-hass and they show up with their pretty names and show the correct state. However, pushing the switch on the toon does not change the state of the lights. Turning the lights on or off in home assistant does change the state on the toon.

Is there any way I can debug what is going on either on the toon or on the home assistant side?

**Comment by Luc-S** [comment]
Which Toon do you have (Toon 1 or a new 2)? Because the connection appears to be OK (states are updating and friendly names are retrieved) maybe you aren't pressing on the correct location? You have to press the little switch image.

The app isn't optimised for Toon 2 so maybe the 'hitboxes' aren't correctly aligned with the images.

Can you share one of the object names you have added as switch? This app is only able to control:

- 8 sensors
- 4 scenes
- 5 switches/input_booleans
- 1 input_number (max 6 options)
- 1 custom alarm

So if you have a 'light.livingroom' this can not be controlled. To work around this, maybe you can create a custom switch in the background that switches the light.livingroom.

**Comment by Luc-S** [comment]
I have a switch in my configuration.yaml (switch.set_stage_to_5) which sets an input_number to value 5 which may help you out. 

If some external control sets the stage to 5, this switch will also be turned ON so it represents the correct value. This is done by the value_template.

```
switch:
  - platform: template
    switches:
      set_stage_to_5:
        value_template: >-
          {% if is_state('input_number.blinds', '5.0') %}
            on
          {% else %}
            off
          {% endif %}
        turn_on:
          service: input_number.set_value
          data:
            entity_id: input_number.blinds
            value: '5.0'
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.set_stage_to_5
            value: false
```

If I would change this code to a light, I think it would become something like below for a made up switch called 'switch.lightSwitch1'. I haven't been able to test this so I hope you will be able to figure it out:

```
switch:
  - platform: template
    switches:
      lightSwitch1:
        value_template: >-
          {% if is_state('light.livingroom', 'on') %}
            on
          {% else %}
            off
          {% endif %}
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.livingroom
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.livingroom
```
